server:
  port: 9081

spring:
  application:
    name:  EXAMPLE-CUSTOMER
    description: 微服务消费用例
    version: 1.0.0-SNAPSHOT
#  primaryDataSource: spring.datasource.main
  datasource:
#    url: jdbc:mysql://rm-2zen4fcwysho855vp.mysql.rds.aliyuncs.com:3306/api?characterEncoding=UTF-8&useSSL=false
#    password: 1q2w3e4R
#    username: base_user
    druid:
      url: jdbc:mysql://rm-2zen4fcwysho855vp.mysql.rds.aliyuncs.com:3306/api?characterEncoding=UTF-8&useSSL=false
      password: 1q2w3e4R
      username: base_user
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 2
      max-active: 10
  redis:
    databases: 0
    ports: 6379
    hosturl: localhost
    expire: 60
  cache:
    timeout: 2000
    capacity: 2


eureka:
   instance:
#      ip-address: ${spring.cloud.client.ip-address}
      prefer-ip-address: true
      #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）_开发配置
      lease-renewal-interval-in-seconds: 5
      #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）_开发配置
      lease-expiration-duration-in-seconds: 10
#      instance-id: ${spring.cloud.client.ip-address}:${server.port}
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.int[1,9]}}--${spring.application.version}
   client:
     healthcheck:
       enabled: true
     service-url:
       defaultZone: http://localhost:8761/eureka/
     register-with-eureka: true
     fetch-registry: true
     # 是否启用Eureka
     enabled: false
     registry-fetch-interval-seconds: 10

#actuator health check
management:
  health:
    redis:
      enabled: false
    db:
      enabled: true
  endpoint:
    health:
      show-details: always
      enabled: true
    httptrace:
      enabled: true
  server:
    status : 500002

#actuator info
info:
  app:
    name:  ${spring.application.name}
    description: ${spring.application.description}
    version: ${spring.application.version}
